name: build-and-deploy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Guess tag for Docker images
        id: prepare
        uses: jupyter-naas/docker-smart-tag-action@1.0.0
        with:
          docker_image: steemit/hive2elastic
          default_branch: ${{ github.event.repository.default_branch }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.prepare.outputs.tag }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
